' *******************************************************************************
' Copyright (c) 2025 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml
participant Client_1 <<component user>>
participant SOCom
participant Server <<component user>>
autonumber
activate Server

activate Client_1

Client_1 -> SOCom : subscribe_event(x, update)
activate SOCom

SOCom -> Server : on_event_subscription_change(x, subscribed)
activate Server

return

return

== ... ==

Server -> Server : updated event

Server -> SOCom : allocate_event_payload(x)
activate SOCom
SOCom -> Client_1 : on_event_payload_allocate(x)
activate Client_1
return writable_payload
return writable_payload

Server -> SOCom : update_event(x, payload)
activate SOCom

SOCom -> Client_1 : on_event_update(x, payload)
activate Client_1
return

return

== ... ==

Client_1 -> SOCom : unsubscribe_event(x)
activate SOCom

SOCom -> Server : on_event_subscription_change(x, unsubscribed)
activate Server
return

return
@enduml
