#!/bin/bash

# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

set -e

echo "Container using someipd started"

# Add multicast route
route add -net 224.0.0.0/4 dev eth0

# Automatically startup gatewayd and someipd:
# gatewayd --> connects to car_window_controller, sets up IPC communication to someipd
# someipd --> connects to gatewayd, sends out SOME/IP messages on the network

/home/source/bazel-bin/score/gatewayd/gatewayd --service_instance_manifest /home/source/score/gatewayd/etc/mw_com_config.json --configuration /home/source/bazel-bin/score/config/mw_someip_config.bin &
# Give gatewayd some time to start. TODO: improve with some sort of state check
sleep 2s

VSOMEIP_CONFIGURATION="$(pwd)/tests/integration/vsomeip.json"
export VSOMEIP_CONFIGURATION
/home/source/bazel-bin/score/someipd/someipd --service_instance_manifest /home/source/score/someipd/etc/mw_com_config.json --configuration /home/source/bazel-bin/score/config/mw_someip_config.bin &

# /home/source/bazel-bin/tests/benchmarks/ipc_benchmarks

sleep infinity
