# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Cache maintenance

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  repository_cache_maintenance:
    permissions:
      actions: write # needed for cache deletion at setup-bazel-cache
      contents: read
    secrets: inherit
    uses: eclipse-score/cicd-workflows/.github/workflows/cache-maintenance.yml@improved-caching
    with:
      variants: |
        x86_64-linux|//...
        aarch64-linux|//...
        x86_64-qnx|//src/... //tests/...
        aarch64-qnx|//src/... //tests/...

  ci:
    needs:
      - repository_cache_maintenance
    permissions:
      actions: write # needed for cache deletion at setup-bazel-cache
      contents: read
    secrets: inherit
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/ci.yml

  ci_pull_request_target:
    needs:
      - repository_cache_maintenance
    permissions:
      actions: write # needed for cache deletion at setup-bazel-cache
      contents: write
      pages: write
      pull-requests: write
      id-token: write
      issues: write
    secrets: inherit
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/ci_pull_request_target.yml
