# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Cache maintenance

# Refreshes caches and rebuilds a new bazel repository cache when MODULE.bazel.lock changes.
# Caches are only saved on pushes to the main branch or on workflow_dispatch events.
# In merge_groups and pull requests a fast dry-run is executed to ensure caches can be rebuilt successfully.

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  repository_cache_maintenance:
    permissions:
      actions: write # needed for cache deletion after cache refresh
      contents: read
    secrets:
      score-qnx-license: ${{ secrets.SCORE_QNX_LICENSE }}
      score-qnx-user: ${{ secrets.SCORE_QNX_USER }}
      score-qnx-password: ${{ secrets.SCORE_QNX_PASSWORD }}
    uses: eclipse-score/cicd-workflows/.github/workflows/cache-maintenance.yml@make-cache-maintenance-executable-in-merge-queue
    with:
      variants: |
        //...
        --config=qemu-integration //quality/... //tests/...
        --config=x86_64-linux //...
        --config=aarch64-linux //...
        --config=x86_64-qnx //quality/... //score/... //tests/...
        --config=aarch64-qnx //quality/... //score/... //tests/...

  ci:
    needs:
      - repository_cache_maintenance
    secrets: inherit
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/ci.yml

  ci_pull_request_target:
    needs:
      - repository_cache_maintenance
    permissions:
      contents: write
      pages: write
      pull-requests: write
      id-token: write
      issues: write
    secrets: inherit
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/ci_pull_request_target.yml

  delete_old_caches:
    runs-on: ubuntu-24.04
    needs:
      - ci
      - ci_pull_request_target
    permissions:
      actions: write # needed for deletion of old caches
      contents: read
    if: ${{ !cancelled() && github.event_name == 'push' }}
    steps:
      - name: Prune obsolete Bazel caches
        uses: eclipse-score/cicd-actions/prune-cache@8e69f47b45778afd3b0d069c0456184c4ceeffe7
